project:
  type: website

website:
  title: "statapps"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - clustering.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/jtr13/statapps
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Joyce Robbins"

format:
  html:
    theme: [cerulean, style/edav3.scss]
    code-link: true
    highlight-style: style/joyce.theme
    callout-icon: false
    fig-width: 4
    fig-height: 3

knitr:
  opts_chunk:
    fig.align: center
    out.width: 50%

execute:
  echo: true
  warning: false
  message: false
  error: true
  cache: false

editor:
  source

